spring.application.name=BookSeller

#Database config
#spring.datasource.url=jdbc:postgresql://db.qdmhtmaiikazqdokgypx.supabase.co:5432/postgres?sslmode=require
#spring.datasource.username=postgres
#spring.datasource.password=NghiaDepZai
#database config

spring.datasource.url=jdbc:postgresql://localhost:5432/bookseller_db
spring.datasource.username=buiviethung
spring.datasource.password=
#spring.jpa.properties.hibernate.default_schema=itss
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


#spring.jpa.hibernate.ddl-auto=update

# CORS configuration
spring.web.cors.allowed-origins=http://localhost:3000
spring.web.cors.allowed-methods=GET,POST,PUT,DELETE,OPTIONS
spring.web.cors.allowed-headers=*

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=duongnghia2904204@gmail.com
spring.mail.password=wjzc jhid fyfp wyjk
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true




#spring.jpa.hibernate.ddl-auto=none
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect